version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build stated on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
artifacts:
  files:
    - target/webapp-0.0.1-SNAPSHOT.war